language: php
php:
  - 5.5
  - 5.4
  - 5.3
branches: 
  only: 
    - master
before_install:
  - PROJECT_DIR=$(pwd)
install:
  - cd /tmp
  - git clone https://github.com/zenovich/runkit.git
  - cd runkit
  - git checkout 1.0.3
  - sudo pecl install package.xml
  - PHP_INI=$(php --ini | grep "Loaded Configuration File" | awk '{print $4}')
  - echo "extension=runkit.so" >> $PHP_INI
  - echo "runkit.internal_override = TRUE" >> $PHP_INI
before_script:  
  - cd ~/function_mock/test
script: phpunit function_mock.test.php
